### ISSUE TITLE
Ratings Map - Write to Dynamo

### ISSUE THREAD

**Issue by pmkuny** [pmkuny/movie-scraper#2]
Still need to figure out how to properly assign the type to this one.  Dict, list. str? Who knows!
_Originally posted by @aidutcher in https://github.com/pmkuny/movie-scraper/pull/1#discussion_r622660027_

Current Line:
```
':ratings': {'L': item['Ratings']},
```

Sample Data:

```
    "Poster": "https://m.media-amazon.com/images/M/MV5BOGI5NjI1NjMtMjg4Mi00YTQyLThkYjgtNTI1YjlhNzZkOTZmXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
    "Ratings": [
        {
            "Source": "Internet Movie Database",
            "Value": "6.1/10"
        }
    ],
    "Metascore": "N/A",
```

Still need to figure out the proper way to write a list of dictionaries to a Dynamo Table:

```
Traceback (most recent call last):
  File "./movie.py", line 212, in <module>
    update_table(movie_content,"movies")
  File "./movie.py", line 122, in update_table
    response = g_ddb_client.update_item(
  File "/home/kunyp/.local/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/kunyp/.local/lib/python3.8/site-packages/botocore/client.py", line 648, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/home/kunyp/.local/lib/python3.8/site-packages/botocore/client.py", line 696, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/home/kunyp/.local/lib/python3.8/site-packages/botocore/validate.py", line 293, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in ExpressionAttributeValues.:ratings.L[0]: "Source", must be one of: S, N, B, SS, NS, BS, M, L, NULL, BOOL
Unknown parameter in ExpressionAttributeValues.:ratings.L[0]: "Value", must be one of: S, N, B, SS, NS, BS, M, L, NULL, BOOL
```

**Comment by pmkuny** [comment]
From a `help wanted` standpoint, I would love if someone could comment on here and explain why this issue is occurring and how to fix it.

**Comment by pmkuny** [comment]
Sample Data:

```
    "Ratings": [
        {
            "Source": "Internet Movie Database",
            "Value": "6.1/10"
        }
    ],
```
using ` ':ratings': {'L': '{}'.format(item['Ratings'][0])}`

gives the following error:

```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter ExpressionAttributeValues.:ratings.L, value: {'Source': 'Internet Movie Database', 'Value': '5.6/10'}, type: <class 'str'>, valid types: <class 'list'>, <class 'tuple'>

```
